.\"	$OpenBSD$
.\"
.\" Copyright (c) 2024 The OpenBSD project
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt ENA 4
.Os
.Sh NAME
.Nm ena
.Nd Amazon Elastic Network Adapter
.Sh SYNOPSIS
.Cd "ena* at pci?"
.Sh DESCRIPTION
The
.Nm
driver supports the Amazon Elastic Network Adapter (ENA), the
paravirtualised network interface found on
.Dq Nitro
generation Amazon EC2 instances, including the
.Cm t3 ,
.Cm m5 ,
.Cm m6 ,
.Cm m7 ,
.Cm c5 ,
.Cm c6 ,
.Cm c7 ,
and
.Cm r5
instance families and their variants.
.Pp
The adapter presents itself as either a physical function or an
SR-IOV virtual function.
The driver negotiates the number of hardware queues, the receive and
transmit ring sizes, and any supported checksum offload capabilities
with the device at attach time.
.Sh SEE ALSO
.Xr arp 4 ,
.Xr ifmedia 4 ,
.Xr intro 4 ,
.Xr netintro 4 ,
.Xr pci 4 ,
.Xr hostname.if 5 ,
.Xr ifconfig 8
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 7.9 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written for
.Ox
by
.An the OpenBSD project
over the Amazon
.Sy ena-com
hardware abstraction layer.
.Sh CAVEATS
The
.Nm
driver does not yet implement TSO or the device's low-latency queue
(LLQ) transmit mode.
